# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "hashicorp/precise32"
    config.vm.hostname = "beancounter-dev.xpeppers.com"
    config.vm.network :forwarded_port, guest: 80, host: 8080

    config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024"]
      vb.customize ["modifyvm", :id, "--cpus", "2"]
    end

    config.vm.provision :shell, :path => "upgrade-puppet.sh"

    config.vm.provision :puppet do |puppet|
      puppet.options = "--verbose"
      puppet.module_path     = "../modules"
      puppet.manifests_path    = "../manifests"
      puppet.manifest_file     = "init.pp"
    end

    config.vm.provision :puppet do |puppet|
      puppet.options = "--verbose"
      puppet.manifest_file     = "init.pp"
      puppet.module_path     = "../modules"
    end
end
